original_command_list = [
    "advancement",
    "attribute",
    "bossbar",
    "clear",
    "clone",
    "data",
    "datapack",
    "debug",
    "defaultgamemode",
    "difficulty",
    "effect",
    "enchant",
    "execute",
    "experience",
    "fill",
    "forceload",
    "function",
    "gamemode",
    "gamerule",
    "give",
    "help",
    "kick",
    "kill",
    "list",
    "locate",
    "locatebiome",
    "loot",
    "me",
    "message",
    "particle",
    "playsound",
    "publish",
    "recipe",
    "reload",
    "replaceitem",
    "say",
    "schedule",
    "scoreboard",
    "seed",
    "setblock",
    "setworldspawn",
    "spawnpoint",
    "spectate",
    "spreadplayers",
    "stopsound",
    "summon",
    "tag",
    "team",
    "teammsg",
    "teleport",
    "tell",
    "tellraw",
    "title",
    "tm",
    "tp",
    "trigger",
    "w",
    "weather",
    "worldborder",
    "xp"
]

my_commands = {}

for new_command in my_commands.keys():
    if new_command in original_command_list:
        raise RuntimeError(new_command + " is already an existing minecraft command!")
